kotlin.code.style=official
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Loader
minecraft_version=1.20.1
minecraft_version_range=[1.20,1.21)
forge_version=47.4.2
forge_version_range=[46,)
kff_version=4.11.0

# Mappings
parchment_version = 2023.09.03
mapping_channel=official
mapping_version=1.20.1

# Mod
mod_id=neodonium
mod_name=Neodonium
mod_version=1.0.0
mod_authors=TheEnderCore, Astra, DuskAutumnStorm
mod_description=Evil Alex's Caves Addon
mod_license=All rights reserved
# Used in maven publishing, should match mod sources: https://maven.apache.org/guides/mini/guide-naming-conventions.html
mod_group_id=org.teamvoided.neodonium


# Dependencies
citadel_version=2.6.1
alexs_caves_version=2.0.2

player_anim=1.0.2-rc1+1.20

# Dev
jei_version=15.20.0.112
emi_version=1.1.22+1.20.1

